[package]
name = "matrix_rain"
authors = ["Shresht7"]
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
clap = "4.0.7"
crossterm = "0.25"
rand = "0.8.5"