[package]
name = "matrix_rain"
authors = ["Shresht7"]
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
clap = "3.2.8"
crossterm = "0.24"
rand = "0.8.5"